name: Build Docs
on:
  push:
    branches:
      - master

jobs:
  build-docs:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout 🛎️
        # If you're using actions/checkout@v2 you must
        # set persist-credentials to false in most cases
        # for the deployment to work correctly.
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Set up Python 3.6
        uses: actions/setup-python@v4
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          ./ci/install_dependencies.sh docs
      - name: Build Docs
        run: |
          cd docs
          make html
      - name: Deploy Docs 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: docs/build/html # The folder the action should deploy.
